[features]
seeds = false
skip-lint = false

[programs.localnet]
shitpost_pro = "62gJC6oneEykVGdAq7Lr2x5bw33B3CnmHVHeeCxkZ7yJ"

[programs.devnet]
shitpost_pro = "62gJC6oneEykVGdAq7Lr2x5bw33B3CnmHVHeeCxkZ7yJ"

[programs.mainnet]
shitpost_pro = "62gJC6oneEykVGdAq7Lr2x5bw33B3CnmHVHeeCxkZ7yJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
